export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
};

export const MESSAGES = {
  SUCCESS: "Operation successful",
  ERROR: "An error occurred",
  NOT_FOUND: "Resource not found",
  UNAUTHORIZED: "Unauthorized access",
};

export const ERROR_CODE = {
  INVALID_ID: "INVALID_ID",
  DUPLICATE_FILED: "DUPLICATE_FILED",
  VALIDATION_DB_ERROR: "VALIDATION_DB_ERROR",
  INVALID_JWT_TOKEN: "INVALID_JWT_TOKEN",
  FORGOT_PASSWORD_ERROR: "FORGOT_PASSWORD_ERROR",
};
